# Generated by Django 4.0.5 on 2022-06-15 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('intro', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.IntegerField()),
                ('school', models.CharField(max_length=100)),
                ('branch', models.CharField(max_length=100)),
                ('college', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=100)),
                ('codeforces', models.CharField(max_length=20)),
                ('codechef', models.CharField(max_length=20)),
                ('projects', models.CharField(max_length=500)),
                ('github', models.CharField(max_length=20)),
                ('skills', models.CharField(max_length=200)),
                ('achievement', models.CharField(max_length=200)),
                ('experience', models.CharField(max_length=200)),
            ],
        ),
    ]
