# Generated by Django 4.0.5 on 2022-06-15 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='data',
            name='leetcode',
            field=models.CharField(default='NA', max_length=20),
        ),
    ]
