# Generated by Django 4.0.5 on 2022-06-16 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_data_username_alter_data_leetcode_alter_data_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='username',
            field=models.CharField(max_length=20),
        ),
    ]
